---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cleanup-namespace-delete
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-cleanup-namespace-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-cleanup-namespace-delete
subjects:
- kind: ServiceAccount
  name: kyverno-cleanup-controller
  namespace: kyverno
